language: node_js
node_js:
- node
deploy:
  provider: npm
  email: ken@hoff.tech
  on:
    tags: true
  api_key:
    secure: SlGDD3ZVJ+lTPeNOh7PyrjU7oc9PjSKpHGW3qvzK1jbOURCDP3DqGuxEoDZCeR3lWbeqWMDcuRen1MCX0bkVo+hoM2YDgS3Zn77ZBIDI43NkBqP3jEvypT3gBtjmGMEfA4LTJrXy2BGgixa6XrNUhZ8vBWP2xsdkD+goUjmflFbMxvk16aUQkv/bP+rrdyyn2+bwMxJ7BvELtMqxT2ScWoSfwqgR4S7u5m8i606GRrovvmxe1dO27yABv1TgS8zYLAzF1bz47rPD8QtDwcHNaS9dnqSpyYUz4PjPRPXSOFh8AV0BwyNswy+9KfqKpWK4gu45FvI9hC4riUTX7A+ozEclB6eHN3ydPvbb+lyvexBVUaS96CvtKqAUQgGSQJ0zjZvw122wxkYNADVDYgo7yMAeMgEGLIeZaeniVntHypGStnKRUReSR9T+MljknTvRU7VZB3jPVdAAmsJnvgvXhv7Saz5SsBKDljq2VJzeFbec8emhHyFnWBlm7VBT/w0ohuWo7xvNK4BH0c+zn+kIXEcIWZuwT3rwcmn2Ry32TAC0AtWW2pKw5PmJL0bWSceOzCIq5nayAJD8+UXYmuVjLZgv30vpKkAXwTdLNQVLiu4NdW/BuWRqd9w0c2dn1S5QrOUQrtgPVEW5ubsmzzZaVwocWedWmzSBiGVl7/lBeIE=
